create table if not exists schools (
  id text primary key,
  short_name text,
  full_name text,
  city text,
  state text,
  mascot text,
  colors text,
  division text,
  conference text,
  logo_path text
);

insert into schools (id, short_name, full_name, city, state, mascot, colors, division, conference, logo_path)
values
  ('msd', 'MSD', 'Maryland School for the Deaf', 'Frederick', 'MD', 'Orioles', 'Orange and Black', 'd1', 'Big 6', '/logos/msd.png'),
  ('mssd', 'MSSD', 'Model Secondary School for the Deaf', 'Washington', 'DC', 'Eagles', 'Red, White and Dark Blue', 'd1', 'Big 6', '/logos/mssd.png'),
  ('csd-fremont', 'CSDF', 'California School for the Deaf, Fremont', 'Fremont', 'CA', 'Eagles', 'Orange and Black', 'd1', 'Big 6', '/logos/csdf.png'),
  ('csd-riverside', 'CSDR', 'California School for the Deaf, Riverside', 'Riverside', 'CA', 'Cubs', 'Scarlet and Grey', 'd1', 'Big 6', '/logos/csdr.png'),
  ('isd', 'ISD', 'Indiana School for the Deaf', 'Indianapolis', 'IN', 'Orioles', 'Orange and Black', 'd1', 'Big 6', '/logos/isd.png'),
  ('tsd', 'TSD', 'Texas School for the Deaf', 'Austin', 'TX', 'Rangers', 'Blue and White', 'd1', 'Big 6', '/logos/tsd.png'),
  ('lexington', 'LSD', 'Lexington School for the Deaf', 'East Elmhurst', 'NY', 'Blue Jays', null, 'd2', 'ESDAA 1', null),
  ('osd', 'OSD', 'Ohio School for the Deaf', 'Columbus', 'OH', 'Spartans', null, 'd2', 'ESDAA 1', null),
  ('asd', 'ASD', 'American School for the Deaf', 'Hartford', 'CT', 'Tigers', null, 'd2', 'ESDAA 1', null),
  ('dsd', 'DelSD', 'Delaware School for the Deaf', 'Newark', 'DE', 'Blue Hawks', null, 'd2', 'ESDAA 1', null),
  ('katzenbach', 'KSD', 'Marie H. Katzenbach School for the Deaf', 'Trenton', 'NJ', 'Colts', null, 'd2', 'ESDAA 1', null),
  ('tlc', 'TLC', 'The Learning Center for the Deaf', 'Framingham', 'MA', 'Galloping Ghosts', null, 'd2', 'ESDAA 1', null),
  ('wpsd', 'WPSD', 'Western Pennsylvania School for the Deaf', 'Edgewood', 'PA', 'Lions', null, 'd2', 'ESDAA 1', null),
  ('baxter', 'GBSD', 'Governor Baxter School for the Deaf', 'Falmouth', 'ME', 'Islanders', null, 'd2', 'ESDAA 2', null),
  ('nyssd', 'NYSSD', 'New York State School for the Deaf', 'Rome', 'NY', 'Trojans', null, 'd2', 'ESDAA 2', null),
  ('rsd', 'RSD', 'Rochester School for the Deaf', 'Rochester', 'NY', 'Wildcats', null, 'd2', 'ESDAA 2', null),
  ('wvsdb', 'WVSDB', 'West Virginia Schools for the Deaf and Blind', 'Romney', 'WV', 'Lions', null, 'd2', 'ESDAA 2', null),
  ('arkansas-sd', 'ASD-AR', 'Arkansas School for the Deaf', 'Little Rock', 'AR', 'Leopards', null, 'd2', 'GPSD', null),
  ('iowa-sd', 'ISD-IA', 'Iowa School for the Deaf', 'Council Bluffs', 'IA', 'Bobcats', null, 'd2', 'GPSD', null),
  ('kssd', 'KSD', 'Kansas State School for the Deaf', 'Olathe', 'KS', 'Jackrabbits', null, 'd2', 'GPSD', null),
  ('msad', 'MSAD', 'Minnesota State Academy for the Deaf', 'Faribault', 'MN', 'Trojans', null, 'd2', 'GPSD', null),
  ('missouri-sd', 'MSD-MO', 'Missouri School for the Deaf', 'Fulton', 'MO', 'Eagles', null, 'd2', 'GPSD', null),
  ('nmsd', 'NMSD', 'New Mexico School for the Deaf', 'Santa Fe', 'NM', 'Roadrunners', null, 'd2', 'GPSD', null),
  ('ndsd', 'NDSD', 'North Dakota School for the Deaf', 'Devils Lake', 'ND', 'Bulldogs', null, 'd2', 'GPSD', null),
  ('oklahoma-sd', 'OSD-OK', 'Oklahoma School for the Deaf', 'Sulphur', 'OK', 'Bison', null, 'd2', 'GPSD', null),
  ('wisconsin-sd', 'WSD', 'Wisconsin School for the Deaf', 'Delavan', 'WI', 'Firebirds', null, 'd2', 'GPSD', null),
  ('aidb', 'AIDB', 'Alabama Institute for the Deaf and Blind', 'Talladega', 'AL', 'Silent Warriors', null, 'd2', 'MDSDAA', null),
  ('encsd', 'ENCSD', 'Eastern North Carolina School for the Deaf', 'Wilson', 'NC', 'Fighting Hornets', null, 'd2', 'MDSDAA', null),
  ('fsdb', 'FSDB', 'Florida School for the Deaf and Blind', 'St. Augustine', 'FL', 'Dragons', null, 'd2', 'MDSDAA', null),
  ('gsd-ga', 'GSD', 'Georgia School for the Deaf', 'Cave Spring', 'GA', 'Tigers', null, 'd2', 'MDSDAA', null),
  ('ksd-ky', 'KSD-KY', 'Kentucky School for the Deaf', 'Danville', 'KY', 'Colonels', null, 'd2', 'MDSDAA', null),
  ('lsd-la', 'LSD-LA', 'Louisiana School for the Deaf', 'Baton Rouge', 'LA', 'War Eagles', null, 'd2', 'MDSDAA', null),
  ('msd-ms', 'MSD-MS', 'Mississippi School for the Deaf', 'Jackson', 'MS', 'Bulldogs', null, 'd2', 'MDSDAA', null),
  ('ncsd', 'NCSD', 'North Carolina School for the Deaf', 'Morganton', 'NC', 'Bears', null, 'd2', 'MDSDAA', null),
  ('scsdb', 'SCSDB', 'South Carolina School for the Deaf and Blind', 'Spartanburg', 'SC', 'Hornets', null, 'd2', 'MDSDAA', null),
  ('tsd-tn', 'TSD-TN', 'Tennessee School for the Deaf', 'Knoxville', 'TN', 'Vikings', null, 'd2', 'MDSDAA', null),
  ('vsdb', 'VSDB', 'Virginia School for the Deaf and the Blind', 'Staunton', 'VA', 'Cardinals', null, 'd2', 'MDSDAA', null),
  ('csdb', 'CSDB', 'Colorado School for the Deaf and Blind', 'Colorado Springs', 'CO', 'Bulldogs', null, 'd2', 'Independent', null),
  ('hsdb', 'HSDB', 'Hawaii School for the Deaf and the Blind', 'Honolulu', 'HI', 'Dolphins', null, 'd2', 'Independent', null),
  ('illinois-sd', 'ISD-IL', 'Illinois School for the Deaf', 'Jacksonville', 'IL', 'Tigers', null, 'd2', 'Independent', null),
  ('michigan-sd', 'MSD-MI', 'Michigan School for the Deaf', 'Flint', 'MI', 'Tartars', null, 'd2', 'Independent', null);
