create table if not exists teams (
  id text primary key,
  school_id text references schools(id),
  sport text,
  level text,
  gender text,
  division text,
  team_name text
);

insert into teams (id, school_id, sport, level, gender, division, team_name)
values
  ('msd-bkb-boys-d1', 'msd', 'basketball', 'hs', 'boys', 'd1', 'MSD'),
  ('mssd-bkb-boys-d1', 'mssd', 'basketball', 'hs', 'boys', 'd1', 'MSSD'),
  ('csd-fremont-bkb-boys-d1', 'csd-fremont', 'basketball', 'hs', 'boys', 'd1', 'CSDF'),
  ('csd-riverside-bkb-boys-d1', 'csd-riverside', 'basketball', 'hs', 'boys', 'd1', 'CSDR'),
  ('isd-bkb-boys-d1', 'isd', 'basketball', 'hs', 'boys', 'd1', 'ISD'),
  ('tsd-bkb-boys-d1', 'tsd', 'basketball', 'hs', 'boys', 'd1', 'TSD'),
  ('lexington-bkb-boys-d2', 'lexington', 'basketball', 'hs', 'boys', 'd2', 'LSD'),
  ('osd-bkb-boys-d2', 'osd', 'basketball', 'hs', 'boys', 'd2', 'OSD'),
  ('asd-bkb-boys-d2', 'asd', 'basketball', 'hs', 'boys', 'd2', 'ASD'),
  ('dsd-bkb-boys-d2', 'dsd', 'basketball', 'hs', 'boys', 'd2', 'DelSD'),
  ('katzenbach-bkb-boys-d2', 'katzenbach', 'basketball', 'hs', 'boys', 'd2', 'KSD'),
  ('tlc-bkb-boys-d2', 'tlc', 'basketball', 'hs', 'boys', 'd2', 'TLC'),
  ('wpsd-bkb-boys-d2', 'wpsd', 'basketball', 'hs', 'boys', 'd2', 'WPSD'),
  ('baxter-bkb-boys-d2', 'baxter', 'basketball', 'hs', 'boys', 'd2', 'GBSD'),
  ('nyssd-bkb-boys-d2', 'nyssd', 'basketball', 'hs', 'boys', 'd2', 'NYSSD'),
  ('rsd-bkb-boys-d2', 'rsd', 'basketball', 'hs', 'boys', 'd2', 'RSD'),
  ('wvsdb-bkb-boys-d2', 'wvsdb', 'basketball', 'hs', 'boys', 'd2', 'WVSDB'),
  ('arkansas-sd-bkb-boys-d2', 'arkansas-sd', 'basketball', 'hs', 'boys', 'd2', 'ASD-AR'),
  ('iowa-sd-bkb-boys-d2', 'iowa-sd', 'basketball', 'hs', 'boys', 'd2', 'ISD-IA'),
  ('kssd-bkb-boys-d2', 'kssd', 'basketball', 'hs', 'boys', 'd2', 'KSD'),
  ('msad-bkb-boys-d2', 'msad', 'basketball', 'hs', 'boys', 'd2', 'MSAD'),
  ('missouri-sd-bkb-boys-d2', 'missouri-sd', 'basketball', 'hs', 'boys', 'd2', 'MSD-MO'),
  ('nmsd-bkb-boys-d2', 'nmsd', 'basketball', 'hs', 'boys', 'd2', 'NMSD'),
  ('ndsd-bkb-boys-d2', 'ndsd', 'basketball', 'hs', 'boys', 'd2', 'NDSD'),
  ('oklahoma-sd-bkb-boys-d2', 'oklahoma-sd', 'basketball', 'hs', 'boys', 'd2', 'OSD-OK'),
  ('wisconsin-sd-bkb-boys-d2', 'wisconsin-sd', 'basketball', 'hs', 'boys', 'd2', 'WSD'),
  ('aidb-bkb-boys-d2', 'aidb', 'basketball', 'hs', 'boys', 'd2', 'AIDB'),
  ('encsd-bkb-boys-d2', 'encsd', 'basketball', 'hs', 'boys', 'd2', 'ENCSD'),
  ('fsdb-bkb-boys-d2', 'fsdb', 'basketball', 'hs', 'boys', 'd2', 'FSDB'),
  ('gsd-ga-bkb-boys-d2', 'gsd-ga', 'basketball', 'hs', 'boys', 'd2', 'GSD'),
  ('ksd-ky-bkb-boys-d2', 'ksd-ky', 'basketball', 'hs', 'boys', 'd2', 'KSD-KY'),
  ('lsd-la-bkb-boys-d2', 'lsd-la', 'basketball', 'hs', 'boys', 'd2', 'LSD-LA'),
  ('msd-ms-bkb-boys-d2', 'msd-ms', 'basketball', 'hs', 'boys', 'd2', 'MSD-MS'),
  ('ncsd-bkb-boys-d2', 'ncsd', 'basketball', 'hs', 'boys', 'd2', 'NCSD'),
  ('scsdb-bkb-boys-d2', 'scsdb', 'basketball', 'hs', 'boys', 'd2', 'SCSDB'),
  ('tsd-tn-bkb-boys-d2', 'tsd-tn', 'basketball', 'hs', 'boys', 'd2', 'TSD-TN'),
  ('vsdb-bkb-boys-d2', 'vsdb', 'basketball', 'hs', 'boys', 'd2', 'VSDB'),
  ('csdb-bkb-boys-d2', 'csdb', 'basketball', 'hs', 'boys', 'd2', 'CSDB'),
  ('hsdb-bkb-boys-d2', 'hsdb', 'basketball', 'hs', 'boys', 'd2', 'HSDB'),
  ('illinois-sd-bkb-boys-d2', 'illinois-sd', 'basketball', 'hs', 'boys', 'd2', 'ISD-IL'),
  ('michigan-sd-bkb-boys-d2', 'michigan-sd', 'basketball', 'hs', 'boys', 'd2', 'MSD-MI');
