export const FALLBACK_SCHOOL_OPTIONS = [
  { id: "aidb", full_name: "Alabama Institute for the Deaf and Blind", short_name: "AIDB" },
  { id: "asd", full_name: "American School for the Deaf", short_name: "ASD" },
  { id: "arkansas-sd", full_name: "Arkansas School for the Deaf", short_name: "ASD-AR" },
  { id: "baxter", full_name: "Governor Baxter School for the Deaf", short_name: "GBSD" },
  { id: "csdb", full_name: "Colorado School for the Deaf and Blind", short_name: "CSDB" },
  { id: "csd-fremont", full_name: "California School for the Deaf, Fremont", short_name: "CSDF" },
  { id: "csd-riverside", full_name: "California School for the Deaf, Riverside", short_name: "CSDR" },
  { id: "dsd", full_name: "Delaware School for the Deaf", short_name: "DelSD" },
  { id: "encsd", full_name: "Eastern North Carolina School for the Deaf", short_name: "ENCSD" },
  { id: "fsdb", full_name: "Florida School for the Deaf and Blind", short_name: "FSDB" },
  { id: "gsd-ga", full_name: "Georgia School for the Deaf", short_name: "GSD" },
  { id: "hsdb", full_name: "Hawaii School for the Deaf and the Blind", short_name: "HSDB" },
  { id: "illinois-sd", full_name: "Illinois School for the Deaf", short_name: "ISD-IL" },
  { id: "isd", full_name: "Indiana School for the Deaf", short_name: "ISD" },
  { id: "iowa-sd", full_name: "Iowa School for the Deaf", short_name: "ISD-IA" },
  { id: "katzenbach", full_name: "Marie H. Katzenbach School for the Deaf", short_name: "KSD" },
  { id: "kssd", full_name: "Kansas State School for the Deaf", short_name: "KSD" },
  { id: "ksd-ky", full_name: "Kentucky School for the Deaf", short_name: "KSD-KY" },
  { id: "lexington", full_name: "Lexington School for the Deaf", short_name: "LSD" },
  { id: "lsd-la", full_name: "Louisiana School for the Deaf", short_name: "LSD-LA" },
  { id: "michigan-sd", full_name: "Michigan School for the Deaf", short_name: "MSD-MI" },
  { id: "missouri-sd", full_name: "Missouri School for the Deaf", short_name: "MSD-MO" },
  { id: "msad", full_name: "Minnesota State Academy for the Deaf", short_name: "MSAD" },
  { id: "msd", full_name: "Maryland School for the Deaf", short_name: "MSD" },
  { id: "msd-ms", full_name: "Mississippi School for the Deaf", short_name: "MSD-MS" },
  { id: "mssd", full_name: "Model Secondary School for the Deaf", short_name: "MSSD" },
  { id: "ncsd", full_name: "North Carolina School for the Deaf", short_name: "NCSD" },
  { id: "ndsd", full_name: "North Dakota School for the Deaf", short_name: "NDSD" },
  { id: "nmsd", full_name: "New Mexico School for the Deaf", short_name: "NMSD" },
  { id: "nyssd", full_name: "New York State School for the Deaf", short_name: "NYSSD" },
  { id: "oklahoma-sd", full_name: "Oklahoma School for the Deaf", short_name: "OSD-OK" },
  { id: "osd", full_name: "Ohio School for the Deaf", short_name: "OSD" },
  { id: "rsd", full_name: "Rochester School for the Deaf", short_name: "RSD" },
  { id: "scsdb", full_name: "South Carolina School for the Deaf and Blind", short_name: "SCSDB" },
  { id: "tlc", full_name: "The Learning Center for the Deaf", short_name: "TLC" },
  { id: "tsd", full_name: "Texas School for the Deaf", short_name: "TSD" },
  { id: "tsd-tn", full_name: "Tennessee School for the Deaf", short_name: "TSD-TN" },
  { id: "vsdb", full_name: "Virginia School for the Deaf and the Blind", short_name: "VSDB" },
  { id: "wisconsin-sd", full_name: "Wisconsin School for the Deaf", short_name: "WSD" },
  { id: "wpsd", full_name: "Western Pennsylvania School for the Deaf", short_name: "WPSD" },
  { id: "wvsdb", full_name: "West Virginia Schools for the Deaf and Blind", short_name: "WVSDB" },
];
